# Generated by Django 5.1.6 on 2025-12-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='complete_at',
            new_name='completed_at',
        ),
    ]
