# Generated by Django 5.1.6 on 2025-12-12 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_country_flag_image_alter_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='gamesession',
            name='flags_viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='game_mode',
            field=models.CharField(choices=[('quiz', 'Quiz Mode'), ('flashcard', 'Flashcard Mode')], default='quiz', max_length=20),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='time_elapsed_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='viewed_countries',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
