# Generated by Django 5.1.6 on 2025-12-12 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_alter_gamesession_options_gamesession_flags_viewed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlagProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField(choices=[(1, 'Box 1'), (2, 'Box 2'), (3, 'Box 3'), (4, 'Box 4'), (5, 'Box 5')], default=1, help_text='Leitner box number (1=new, 5=mastered)')),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this flag should be reviewed next')),
                ('total_reviews', models.IntegerField(default=0, help_text='Total number of times reviewed')),
                ('correct_reviews', models.IntegerField(default=0, help_text='Number of correct reviews')),
                ('last_reviewed_at', models.DateTimeField(blank=True, help_text='Last time this flag was reviewed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='apis.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'indexes': [models.Index(fields=['user', 'next_review_date'], name='apis_userfl_user_id_2330ee_idx'), models.Index(fields=['user', 'box_number'], name='apis_userfl_user_id_f193bd_idx')],
                'unique_together': {('user', 'country')},
            },
        ),
    ]
