# Generated by Django 5.1.6 on 2025-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_userflagprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFlagProgress',
        ),
    ]
