# Generated by Django 5.1.6 on 2025-12-12 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_delete_userflagprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={},
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='flags_viewed',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='game_mode',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='total_questions',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='current_country_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='skips_remaining',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='skips_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
