# Generated by Django 5.1.6 on 2025-12-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_alter_gamesession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_emoji',
        ),
    ]
