# Generated by Django 5.1.6 on 2025-12-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_remove_country_flag_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
